apiVersion: v1
kind: Service
metadata:
  name: not-neg-svc
  annotations:
    cloud.google.com/neg: '{"ingress": false}'
spec:
  type: ClusterIP
  selector:
    app: not-neg-deployment
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080